/* Solvly product catalog.
   NOTE FOR OWNER: prices, names and copy are editable here. Each product's
   `art` is a placeholder tile (emoji + brand gradient) — swap in real photos
   by setting `img: "assets/your-photo.jpg"` on any product. */

const SOLVLY_CATEGORIES = [
  { id: "home",      icon: "🏠", name: "Home Organization",  blurb: "Tame the clutter in every room" },
  { id: "car",       icon: "🚗", name: "Car Essentials",     blurb: "A tidier, smarter ride" },
  { id: "travel",    icon: "✈️", name: "Travel Smarter",     blurb: "Pack lighter, move faster" },
  { id: "desk",      icon: "💻", name: "Desk & Productivity", blurb: "A workspace that works" },
  { id: "kitchen",   icon: "🍳", name: "Kitchen Convenience", blurb: "Less mess, more meals" },
  { id: "lifestyle", icon: "✨", name: "Daily Life Hacks",   blurb: "Small fixes, big difference" },
];

const SOLVLY_PRODUCTS = [
  {
    slug: "magnetic-cable-organizer",
    headline: "End Cable Clutter in Seconds",
    name: "Magnetic Cable Organizer Kit",
    category: "home",
    price: 14.99, compareAt: 24.99,
    rating: 4.8, reviews: 214,
    emoji: "🔌",
    tags: ["trending", "best", "under25", "homeup"],
    problem: "Charging cables slide off your desk, tangle behind furniture, and disappear exactly when you need them.",
    solution: "Strong magnetic clips anchor every cable right where you left it — grab, charge, snap back. No drilling, no adhesive mess.",
    benefits: ["Organizes instantly", "No installation", "Holds any cable size", "Works on desks, nightstands & cars"],
  },
  {
    slug: "space-saver-hangers",
    headline: "Double Your Closet Space Overnight",
    name: "Space-Saver Cascading Hangers (6-Pack)",
    category: "home",
    price: 19.99, compareAt: 29.99,
    rating: 4.7, reviews: 168,
    emoji: "👕",
    tags: ["best", "under25", "homeup"],
    problem: "Your closet is packed, hangers are jammed together, and half your clothes end up wrinkled or on the floor.",
    solution: "Cascading hooks let hangers stack vertically, turning one rod slot into six. Same closet — twice the room.",
    benefits: ["Doubles hanging space", "Anti-slip grip", "Holds heavy coats", "Fits any closet rod"],
  },
  {
    slug: "car-seat-gap-organizer",
    headline: "Never Lose Your Phone in the Seat Gap Again",
    name: "Car Seat Gap Organizer",
    category: "car",
    price: 16.99, compareAt: 26.99,
    rating: 4.8, reviews: 305,
    emoji: "🚗",
    tags: ["trending", "best", "under25"],
    problem: "Phones, keys and fries vanish into the black hole between your seat and console — usually while driving.",
    solution: "A slim organizer fills the gap completely and adds pockets for your phone, keys, and cards right at hand level.",
    benefits: ["Blocks the gap fully", "Slides in, no tools", "Fits most vehicles", "Bonus storage pockets"],
  },
  {
    slug: "cordless-mini-car-vacuum",
    headline: "A Spotless Car in Five Minutes",
    name: "Cordless Mini Car Vacuum",
    category: "car",
    price: 34.99, compareAt: 49.99,
    rating: 4.6, reviews: 142,
    emoji: "🌪️",
    tags: ["staff"],
    problem: "Crumbs and dust build up for months because dragging a full-size vacuum to the driveway is a whole project.",
    solution: "A palm-sized cordless vacuum with real suction lives in your glovebox — clean the whole car during one red-light-free playlist.",
    benefits: ["Powerful suction", "USB-C rechargeable", "Fits in the glovebox", "Crevice tools included"],
  },
  {
    slug: "compression-packing-cubes",
    headline: "Pack Twice as Much in the Same Bag",
    name: "Compression Packing Cubes (4-Pack)",
    category: "travel",
    price: 24.99, compareAt: 39.99,
    rating: 4.9, reviews: 261,
    emoji: "🧳",
    tags: ["trending", "best", "travel", "under25"],
    problem: "Your suitcase is full before you're done packing, and finding one shirt means unpacking everything.",
    solution: "Zip-down compression cubes squeeze the air out of your clothes and keep every outfit sorted and visible.",
    benefits: ["Compresses up to 50%", "Sorted by outfit", "Durable zippers", "Carry-on friendly"],
  },
  {
    slug: "universal-travel-adapter",
    headline: "Charge Everything, Anywhere on Earth",
    name: "Universal Travel Adapter",
    category: "travel",
    price: 22.99, compareAt: 34.99,
    rating: 4.7, reviews: 189,
    emoji: "🔋",
    tags: ["travel", "under25", "staff"],
    problem: "Different country, different outlet — and your charger is useless the moment you land.",
    solution: "One adapter covers 150+ countries with built-in USB-C and USB-A ports, so every device charges from a single plug.",
    benefits: ["Works in 150+ countries", "4 devices at once", "Built-in fuse protection", "Pocket sized"],
  },
  {
    slug: "under-desk-cable-tray",
    headline: "A Clean Desk Without Thinking About It",
    name: "Under-Desk Cable Management Tray",
    category: "desk",
    price: 18.99, compareAt: 28.99,
    rating: 4.8, reviews: 174,
    emoji: "🗄️",
    tags: ["best", "under25", "deskup", "homeup"],
    problem: "The cable spaghetti under your desk collects dust, tangles, and ruins an otherwise clean setup.",
    solution: "A steel tray mounts under your desktop and swallows every power strip and cable — out of sight, off the floor.",
    benefits: ["Hides power strips", "Clamp-on, no drilling", "Steel build", "Fits any desk"],
  },
  {
    slug: "adjustable-laptop-stand",
    headline: "Stop Hunching. Start Focusing.",
    name: "Adjustable Aluminum Laptop Stand",
    category: "desk",
    price: 29.99, compareAt: 44.99,
    rating: 4.7, reviews: 233,
    emoji: "💻",
    tags: ["trending", "deskup", "staff"],
    problem: "Hours of looking down at a laptop leaves your neck sore and your posture wrecked.",
    solution: "An aluminum stand lifts your screen to eye level and folds flat when you're done — your spine will notice by Friday.",
    benefits: ["Eye-level screen height", "Folds flat for travel", "Solid aluminum", "Improves airflow & cooling"],
  },
  {
    slug: "multi-chopper",
    headline: "Chop Once. Clean Nothing.",
    name: "Multi-Chopper with Container",
    category: "kitchen",
    price: 27.99, compareAt: 39.99,
    rating: 4.6, reviews: 158,
    emoji: "🥗",
    tags: ["trending", "staff"],
    problem: "Dicing vegetables takes forever, and the cutting board, knife and counter all need cleaning after.",
    solution: "Press once and evenly diced veggies drop straight into the built-in container — prep in minutes, one rinse and done.",
    benefits: ["Dices in one press", "Catches everything", "Dishwasher safe", "Multiple blade inserts"],
  },
  {
    slug: "over-sink-drying-rack",
    headline: "Dry Dishes Without Losing Your Counter",
    name: "Roll-Up Over-Sink Drying Rack",
    category: "kitchen",
    price: 23.99, compareAt: 32.99,
    rating: 4.8, reviews: 121,
    emoji: "🍽️",
    tags: ["under25", "homeup"],
    problem: "The dish rack hogs half your counter and grows a puddle underneath it.",
    solution: "A rack that rolls out over your sink — dishes drip straight down the drain, then it rolls up and disappears into a drawer.",
    benefits: ["Zero counter space", "Drips into the sink", "Rolls up flat", "Doubles as a trivet"],
  },
  {
    slug: "key-finder-tags",
    headline: "Find Your Keys Every Single Time",
    name: "Smart Key Finder Tags (2-Pack)",
    category: "lifestyle",
    price: 21.99, compareAt: 32.99,
    rating: 4.7, reviews: 196,
    emoji: "🔑",
    tags: ["best", "under25", "staff"],
    problem: "You're already late, and your keys are hiding in a coat pocket, couch cushion, or yesterday's bag.",
    solution: "Clip a tag to your keys and make them ring from your phone — or tap the tag to make your phone ring back.",
    benefits: ["Ring from your phone", "Works both ways", "Replaceable battery", "Fits keys, bags & wallets"],
  },
  {
    slug: "motion-sensor-light-strip",
    headline: "Light the Way, Hands Free",
    name: "Motion-Sensor LED Light Strip",
    category: "lifestyle",
    price: 17.99, compareAt: 27.99,
    rating: 4.6, reviews: 133,
    emoji: "💡",
    tags: ["trending", "under25", "homeup"],
    problem: "Midnight trips to the kitchen mean stubbed toes or blinding overhead lights that wake you all the way up.",
    solution: "Stick-anywhere LED strips sense you coming and glow softly, then shut off on their own — closets, hallways, under beds.",
    benefits: ["Auto on/off", "Soft warm glow", "Peel-and-stick install", "Rechargeable battery"],
  },
];

/* Example reviews — REPLACE WITH REAL CUSTOMER REVIEWS before marketing the site.
   These are clearly-written examples to show layout, not real customers. */
const SOLVLY_REVIEWS = [
  { name: "Maya R.", stars: 5, product: "compression-packing-cubes",
    text: "Two weeks in Europe with only a carry-on. My friends checked bags; I breezed past baggage claim every time." },
  { name: "Devon K.", stars: 5, product: "car-seat-gap-organizer",
    text: "My phone slid into the gap on the highway once and I nearly lost my mind. Ordered this that night — problem has literally never happened again." },
  { name: "Priya S.", stars: 5, product: "under-desk-cable-tray",
    text: "I work on camera all day and my desk finally looks like the 'after' photo. Ten-minute install with the clamps." },
  { name: "Jordan T.", stars: 4, product: "motion-sensor-light-strip",
    text: "Put one under the crib-side shelf. 3am feeds no longer require waking the whole house up. Wish I'd bought two." },
];

const SOLVLY_FAQ = [
  { q: "How long does shipping take?", a: "Orders ship within 1–2 business days. Standard delivery takes 7–12 business days, and every order over $50 ships free." },
  { q: "What's the return policy?", a: "30-day hassle-free returns. If a product doesn't solve your problem, send it back for a full refund — no forms, no fine print." },
  { q: "How does it work?", a: "Every Solvly product is chosen for one reason: it fixes a specific everyday frustration without tools, subscriptions, or a manual. Unbox it and it works." },
  { q: "Is there a warranty?", a: "Yes — every product is covered by a 12-month replacement warranty against defects." },
  { q: "Will it work for me?", a: "Product pages list exact compatibility (sizes, vehicles, devices). If you're unsure, message us before ordering and we'll check for you." },
];
