/* Solvly product catalog — real trending problem-solving products (researched July 2026).
   Photos: assets/img/*.jpg, sourced from Unsplash (free to use under the Unsplash License).
   OWNER NOTES:
   - `payLink`: paste a Stripe Payment Link (https://buy.stripe.com/...) per product to
     enable instant card checkout. Until then, orders arrive by email via checkout.html.
   - Swap any `img` for your supplier's real photo when you finalize suppliers. */

const SOLVLY_CATEGORIES = [
  { id: "home",      icon: "🏠", name: "Home Organization",  img: "assets/img/c-home.jpg",    blurb: "Calm starts with a tidy space" },
  { id: "car",       icon: "🚗", name: "Car Essentials",     img: "assets/img/c-car.jpg",     blurb: "A tidier, smarter ride" },
  { id: "travel",    icon: "✈️", name: "Travel Smarter",     img: "assets/img/c-travel.jpg",  blurb: "Pack lighter, breathe easier" },
  { id: "desk",      icon: "💻", name: "Desk & Productivity", img: "assets/img/c-desk.jpg",   blurb: "A workspace that works" },
  { id: "kitchen",   icon: "🍳", name: "Kitchen Convenience", img: "assets/img/c-kitchen.jpg", blurb: "Less mess, more meals" },
  { id: "lifestyle", icon: "✨", name: "Daily Life Hacks",   img: "assets/img/c-life.jpg",    blurb: "Small fixes, big difference" },
];

const SOLVLY_PRODUCTS = [
  {
    slug: "compression-packing-cubes",
    headline: "Pack Twice as Much in the Same Bag",
    name: "Compression Packing Cubes (4-Pack)",
    category: "travel",
    price: 26.99, compareAt: 39.99,
    rating: 4.9, reviews: 261,
    emoji: "🧳", img: "assets/img/p-packing-cubes.jpg",
    payLink: null,
    tags: ["trending", "best", "travel"],
    problem: "Your suitcase is full before you're done packing, and finding one shirt means unpacking everything.",
    solution: "Zip-down compression cubes squeeze the air out of your clothes and keep every outfit sorted and visible.",
    benefits: ["Compresses up to 50%", "Sorted by outfit", "Durable zippers", "Carry-on friendly"],
  },
  {
    slug: "universal-travel-adapter",
    headline: "Charge Everything, Anywhere on Earth",
    name: "Universal Travel Adapter",
    category: "travel",
    price: 22.99, compareAt: 34.99,
    rating: 4.7, reviews: 189,
    emoji: "🔌", img: "assets/img/p-travel-adapter.jpg",
    payLink: null,
    tags: ["travel", "under25", "staff"],
    problem: "Different country, different outlet — and your charger is useless the moment you land.",
    solution: "One adapter covers 150+ countries with built-in USB-C and USB-A ports, so every device charges from a single plug.",
    benefits: ["Works in 150+ countries", "4 devices at once", "Built-in fuse protection", "Pocket sized"],
  },
  {
    slug: "adjustable-laptop-stand",
    headline: "Stop Hunching. Start Focusing.",
    name: "Adjustable Aluminum Laptop Stand",
    category: "desk",
    price: 29.99, compareAt: 44.99,
    rating: 4.7, reviews: 233,
    emoji: "💻", img: "assets/img/p-laptop-stand.jpg",
    payLink: null,
    tags: ["trending", "best", "deskup"],
    problem: "Hours of looking down at a laptop leaves your neck sore and your posture wrecked.",
    solution: "An aluminum stand lifts your screen to eye level and folds flat when you're done — your spine will notice by Friday.",
    benefits: ["Eye-level screen height", "Folds flat for travel", "Solid aluminum", "Improves airflow & cooling"],
  },
  {
    slug: "cable-management-kit",
    headline: "A Clean Desk Without Thinking About It",
    name: "Complete Cable Management Kit",
    category: "desk",
    price: 18.99, compareAt: 27.99,
    rating: 4.8, reviews: 174,
    emoji: "🗄️", img: "assets/img/p-cable-kit.jpg",
    payLink: null,
    tags: ["best", "under25", "deskup", "homeup"],
    problem: "The cable spaghetti on and under your desk collects dust, tangles, and ruins an otherwise calm setup.",
    solution: "Tray, clips, sleeves and ties — everything you need to route every cable out of sight in one afternoon.",
    benefits: ["Hides power strips", "Clamp-on, no drilling", "Fits any desk", "Complete kit, one box"],
  },
  {
    slug: "fast-wireless-charging-pad",
    headline: "Set It Down. It's Charging.",
    name: "Fast Wireless Charging Pad",
    category: "desk",
    price: 19.99, compareAt: 29.99,
    rating: 4.6, reviews: 208,
    emoji: "🔋", img: "assets/img/p-wireless-charger.jpg",
    payLink: null,
    tags: ["trending", "under25", "deskup", "staff"],
    problem: "Plugging and unplugging your phone twenty times a day wears out cables — and your patience.",
    solution: "A slim pad on your desk or nightstand charges your phone the moment you set it down. No cable, no thought.",
    benefits: ["Fast-charge certified", "Case friendly", "No more cable wear", "Soft non-slip surface"],
  },
  {
    slug: "rotating-spice-organizer",
    headline: "Every Spice, One Spin Away",
    name: "360° Rotating Spice Organizer",
    category: "kitchen",
    price: 24.99, compareAt: 36.99,
    rating: 4.8, reviews: 152,
    emoji: "🧂", img: "assets/img/p-spice-rack.jpg",
    payLink: null,
    tags: ["trending", "best", "under25"],
    problem: "The spice cabinet is chaos — you buy a third jar of cumin because you can't find the first two.",
    solution: "A rotating organizer puts every jar label-out at eye level. Spin, grab, cook. The chaos never comes back.",
    benefits: ["360° lazy-susan spin", "Fits standard jars", "Counter or cabinet", "Instant visibility"],
  },
  {
    slug: "rollup-drying-rack",
    headline: "Dry Dishes Without Losing Your Counter",
    name: "Roll-Up Over-Sink Drying Rack",
    category: "kitchen",
    price: 23.99, compareAt: 32.99,
    rating: 4.8, reviews: 121,
    emoji: "🍽️", img: "assets/img/p-dish-rack.jpg",
    payLink: null,
    tags: ["under25", "homeup"],
    problem: "The dish rack hogs half your counter and grows a puddle underneath it.",
    solution: "A rack that rolls out over your sink — dishes drip straight down the drain, then it rolls up and disappears into a drawer.",
    benefits: ["Zero counter space", "Drips into the sink", "Rolls up flat", "Doubles as a trivet"],
  },
  {
    slug: "no-drill-floating-shelves",
    headline: "More Space. Zero Drilling.",
    name: "No-Drill Floating Shelves (Set of 2)",
    category: "home",
    price: 27.99, compareAt: 39.99,
    rating: 4.7, reviews: 143,
    emoji: "📚", img: "assets/img/p-shelves.jpg",
    payLink: null,
    tags: ["trending", "homeup"],
    problem: "You need more storage, but you rent — and your landlord definitely didn't approve wall drilling.",
    solution: "Heavy-duty adhesive mounting puts real shelves on your wall in minutes, holds up to 15 lbs, and comes off clean when you move.",
    benefits: ["No drill, no holes", "Renter friendly", "Holds up to 15 lbs", "Removes clean"],
  },
  {
    slug: "space-saver-hangers",
    headline: "Double Your Closet Space Overnight",
    name: "Space-Saver Cascading Hangers (6-Pack)",
    category: "home",
    price: 19.99, compareAt: 29.99,
    rating: 4.7, reviews: 168,
    emoji: "👕", img: "assets/img/p-hangers.jpg",
    payLink: null,
    tags: ["best", "under25", "homeup"],
    problem: "Your closet is packed, hangers are jammed together, and half your clothes end up wrinkled or on the floor.",
    solution: "Cascading hooks let hangers stack vertically, turning one rod slot into six. Same closet — twice the room.",
    benefits: ["Doubles hanging space", "Anti-slip grip", "Holds heavy coats", "Fits any closet rod"],
  },
  {
    slug: "magnetic-car-phone-mount",
    headline: "Eyes on the Road, Phone in Sight",
    name: "Magnetic Car Phone Mount",
    category: "car",
    price: 16.99, compareAt: 24.99,
    rating: 4.8, reviews: 305,
    emoji: "📱", img: "assets/img/p-car-mount.jpg",
    payLink: null,
    tags: ["trending", "best", "under25"],
    problem: "Your phone slides around the seat while the GPS talks to nobody — and reaching for it is the most dangerous thing you do all day.",
    solution: "A strong magnetic mount holds your phone at eye level. Snap it on one-handed, navigate safely, snap it off when you park.",
    benefits: ["One-hand snap on/off", "Strong hold on bumps", "Any phone, any case", "360° rotation"],
  },
  {
    slug: "cordless-car-vacuum",
    headline: "A Spotless Car in Five Minutes",
    name: "Cordless Mini Car Vacuum",
    category: "car",
    price: 34.99, compareAt: 49.99,
    rating: 4.6, reviews: 142,
    emoji: "🌪️", img: "assets/img/p-car-vacuum.jpg",
    payLink: null,
    tags: ["staff"],
    problem: "Crumbs and dust build up for months because dragging a full-size vacuum to the driveway is a whole project.",
    solution: "A palm-sized cordless vacuum with real suction lives in your glovebox — clean the whole car during one playlist.",
    benefits: ["Powerful suction", "USB-C rechargeable", "Fits in the glovebox", "Crevice tools included"],
  },
  {
    slug: "smart-key-finder",
    headline: "Find Your Keys Every Single Time",
    name: "Smart Key Finder Tag (2-Pack)",
    category: "lifestyle",
    price: 21.99, compareAt: 32.99,
    rating: 4.7, reviews: 196,
    emoji: "🔑", img: "assets/img/p-key-finder.jpg",
    payLink: null,
    tags: ["best", "under25", "staff"],
    problem: "You're already late, and your keys are hiding in a coat pocket, couch cushion, or yesterday's bag.",
    solution: "Clip a tag to your keys and make them ring from your phone — or tap the tag to make your phone ring back.",
    benefits: ["Ring from your phone", "Works both ways", "Replaceable battery", "Fits keys, bags & wallets"],
  },
  {
    slug: "motion-led-strip",
    headline: "Light the Way, Hands Free",
    name: "Motion-Sensor LED Light Strip",
    category: "lifestyle",
    price: 17.99, compareAt: 27.99,
    rating: 4.6, reviews: 133,
    emoji: "💡", img: "assets/img/p-led-strip.jpg",
    payLink: null,
    tags: ["trending", "under25", "homeup"],
    problem: "Midnight trips to the kitchen mean stubbed toes or blinding overhead lights that wake you all the way up.",
    solution: "Stick-anywhere LED strips sense you coming and glow softly, then shut off on their own — closets, hallways, under beds.",
    benefits: ["Auto on/off", "Soft warm glow", "Peel-and-stick install", "Rechargeable battery"],
  },
];

/* Example reviews — REPLACE WITH REAL CUSTOMER REVIEWS before marketing the site.
   These are clearly-written examples to show layout, not real customers. */
const SOLVLY_REVIEWS = [
  { name: "Maya R.", stars: 5, product: "compression-packing-cubes",
    text: "Two weeks in Europe with only a carry-on. My friends checked bags; I breezed past baggage claim every time." },
  { name: "Devon K.", stars: 5, product: "magnetic-car-phone-mount",
    text: "I used to balance my phone on the dash and pray. Now it snaps on at eye level and the GPS finally feels safe to use." },
  { name: "Priya S.", stars: 5, product: "cable-management-kit",
    text: "I work on camera all day and my desk finally looks like the 'after' photo. One quiet Sunday afternoon, done forever." },
  { name: "Jordan T.", stars: 4, product: "motion-led-strip",
    text: "Put one under the crib-side shelf. 3am feeds no longer require waking the whole house up. Wish I'd bought two." },
];

const SOLVLY_FAQ = [
  { q: "How does checkout work?", a: "Place your order and we'll confirm it by email, along with a secure payment link. You're never charged until you approve — no surprises, ever." },
  { q: "How long does shipping take?", a: "Orders ship within 1–2 business days. Standard delivery takes 7–12 business days, and every order over $50 ships free." },
  { q: "What's the return policy?", a: "30-day hassle-free returns. If a product doesn't solve your problem, send it back for a full refund — no forms, no fine print." },
  { q: "Is there a warranty?", a: "Yes — every product is covered by a 12-month replacement warranty against defects." },
  { q: "Will it work for me?", a: "Product pages list exact compatibility (sizes, vehicles, devices). If you're unsure, message us before ordering and we'll check for you." },
];
